language: node_js
node_js:
- '8'
script:
- yarn run build
- yarn run test-nyc
- yarn run coverage
deploy:
  provider: npm
  email: mpomerant@gmail.com
  api_key:
    secure: KrsttY+8Rlc2CLZA00JcLa+VjTqEvVx4mGaqhJQwhj8qo3pyokDIo7u58aDSxl1GyzihF+jWLUYH75qZs7hgY/zmp6ayjolw8KVVSDRWgiHARWX0jHwlCJyB2hQ5UimAfnNT/XexpobbdY9DaoOOTf2A3u+zkYcLndeqi/9TKvhVMBiH/ccGusHnZVuAZlLHc3Z/5BBCbN4tX2ZtQ8wirIdWF/FdcfqClcAbR3OsT2twRJv/0is49gt6oVuSYQ9LcJpS4VUs/NPa6dUMhpNOTpNDr8Fq1Gts4QqaWu/Ky+OrLavrLTNt+XPJXjK2tSyRPfk0WW3dma0VcHBvtSCtoQN6bCzlDfNvd13CqnNO0JmHfAwMG5Rt/h2txHr1aPhw2oeiybopIT7vasoGxpU1RWF57Mb3/D9GMpytUxkIvyFe2/RUom5Bq3hReoOZTrpLDFnTbioC15fdPFXAhPVIbu5vIArkKSmYMxOa1baaTpQAaVMMaQlQmGTL3XmqAuALi/zHgL+o93VtCJoFx556B+LYesLfJ31gkMWeOsAapbEX+unsueml1LIbzQCPtDajl95FFwBEtoacIzluQST4KfLVC4YsSX4HEKEZTXiI4fi938AYTKgJ+Yfy/N/b9hOLr6emnDnph+NrjE7N2MyV+nLD+5tQhbMgZCdOeJLdb78=
  on:
    tags: true
    repo: mpomerant/polljs
